name: Go

on:
  # Allow manually triggering this workflow
  workflow_dispatch:
  # run for all pull requests and pushes to certain branches
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - [self-hosted, linux-arm64]
          - macos-13
          - [self-hosted, macos, arm64]
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version-file: "go.mod"
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
